language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - npm test
env:
  - CI=true

before_deploy:
  - npm run build
  - npm install netlify-cli -g

deploy:
  provider: script
  script: netlify deploy -s b0f1ae20-06e5-4e61-98d7-699719bbe8fa -t c7691ffd874d4a447fe5d871ce3838385268b32b5a61505a56d5826b8d2be87b -p ./build
  skip_cleanup: true
  on:
    branch: master